name         'camptocamp-public_ipaddress'
version      '0.0.1'
source       'https://github.com/camptocamp/puppet-public_ipaddress'
author       'camptocamp'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp Public_Ipaddress Module'
description  'Public Ipaddress Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-public_ipaddress'
